name: Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      nivel_alerta:
        description: "Selecciona nivel de alerta (bajo, medio, alto)"
        required: true
        default: bajo

jobs:
  run-message:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar alerta
        run: echo "Nivel de alerta: ${{ github.event.inputs.nivel_alerta }}"
