name: Issue Comment Workflow

on:
  issue_comment:
    types: [created]

jobs:
  run-message:
    if: github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje por comentario en PR
        run: echo "Comentario en PR detectado"
